### ISSUE TITLE
Error Importing Content Pack

### ISSUE THREAD

**Issue by yalbertob** [ThoZed/graylog-cp-watchguard#17]
Importing the content pack after deleting the old one and the old input show an error. A deep digging on the graylog log report an error about lookups tables (please see attached log).

[log.txt](https://github.com/ThoZed/graylog-cp-watchguard/files/1990954/log.txt)

**Comment by ThoZed** [comment]
Hey There! - just back from enjoying a really long weekend :-)
it seems that the expected lookup table isn't there - maybe it isnt' created because the lookup table file isn't in place.
this is actually not explained in the docs.

Place the <lookup table>.csv Files in /etc/graylog and try again to import the content pack.

https://github.com/ThoZed/graylog-cp-watchguard/blob/master/LookupTables/

Have a nice day :-)

**Comment by ThoZed** [comment]
Hey,

Ran into the same problem:disappointed::sweat_smile:, i could solve it by splitting the content pack into two parts.
i also had to remove all parts from the content pack manually(Lookup Table, Data Adapter, Cache Adapter and Input)

first apply the lookup table and then the input part.
please have a try.

Regards Thomas

Btw: permissions are fine as they are:+1:
